[options]
extend = true
dryrun = false
patch_cache_path = "/Temporary Surge Patches/"

[controller]
name = "TouchOSC"
kind = "Controller"
local_ip = "127.0.0.1"
remote_ip = "127.0.0.1"
remote_port = "53110"
local_port = "53100"

[instrument]
name = "Surge XT"
kind = "Instrument"
local_ip = "127.0.0.1"
remote_ip = "127.0.0.1"
remote_port = "53210"
local_port = "53200"
