[options]
extend = true

[controller]
name = "Surge XT"
kind = "Controller"
local_ip = "192.168.1.110"
remote_ip = "192.168.1.103"
remote_port = "53100"
local_port = "53110"

[instrument]
name = "Surge XT"
kind = "Instrument"
local_ip = "127.0.0.1"
remote_ip = "127.0.0.1"
remote_port = "53210"
local_port = "53200"
